website_project/webapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from webapp import views

# Template tagging
app_name = 'webapp'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^accessrecords/', views.AccRecListView.as_view(), name='accrec'),
    url(r'^register/', views.form_name_view, name='register'),
    url(r'^users/', views.UsersCreateView.as_view(), name='users'),
    url(r'^users_list/$', views.UsersListView.as_view(), name='userlist'),
    url(r'^users_list/(?P<pk>\d+)/$', views.UsersDetailView.as_view(), name='userdetail'),
    url(r'^update/(?P<pk>\d+)/$', views.UsersUpdateView.as_view(), name='userupdate'),
    url(r'^delete/(?P<pk>\d+)/$', views.UsersDeleteView.as_view(), name='userdelete'),
    url(r'^login/$', views.user_login, name='user_login')
]

website_project/website_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from webapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^webapp/', include('webapp.urls', namespace="webapp")),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^special/$', views.special, name='special')
]

website_project/webapp/models.py
from django.db import models
from django.contrib.auth.models import User as Us
from django.urls import reverse



# Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length = 264, unique=True)

    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    topic = models.ForeignKey(Topic, on_delete = models.CASCADE)
    name = models.CharField(max_length = 264, unique = True)
    url = models.URLField(unique = True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage, related_name = 'webpages', on_delete = models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

class User(models.Model):
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    email = models.EmailField()

    def __str__(self):
        return self.first_name

    def get_absolute_url(self):
        return reverse("webapp:index")



class UserProfileInfo(models.Model):
    user = models.OneToOneField(Us, on_delete = models.CASCADE)
    # additional classes
    portfolio_site = models.URLField(blank = True)
    profile_pic = models.ImageField(upload_to = 'profile_pics', blank = True)

    def __str__(self):
        return self.user.username

website_project/webapp/forms.py
from django import forms
from django.core import validators
from webapp.models import User, UserProfileInfo
from django.contrib.auth.models import User as Us

class FormName(forms.Form):

    name = forms.CharField()
    email = forms.EmailField()
    verify_email = forms.EmailField(label='Enter your email again')
    text = forms.CharField(widget = forms.Textarea)
    botcatcher = forms.CharField(required=False, widget=forms.HiddenInput, validators=[validators.MaxLengthValidator(0)])

    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']
        if email != vmail:
            raise forms.ValidationError("Make sure email matches!")


class NewUser(forms.ModelForm):
    class Meta:
        model = User
        fields = '__all__'

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = Us
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

website_project/webapp/views.py
from django.shortcuts import render
from django.views.generic import (TemplateView, DetailView, ListView,
                                  CreateView, UpdateView, DeleteView)
from django.http import HttpResponse, HttpResponseRedirect
from webapp.models import Topic, Webpage, AccessRecord, User
from . import forms
from webapp.forms import UserForm, UserProfileInfoForm
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def index(request):
    dict = {'text': 'I am testing hello function'}
    return render(request, 'webapp/index.html', context=dict)

def form_name_view(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileInfoForm(data = request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print (user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request, 'webapp/form_page.html', {'user_form': user_form,
                                                     'profile_form': profile_form,
                                                     'registered': registered})


class AccRecListView(ListView):
    context_object_name = 'access_records'
    model = AccessRecord
    template_name = 'webapp/access_records.html'



# def accrec(request):
#     webpages_list = AccessRecord.objects.order_by('date')
#     date_dict = {'access_records': webpages_list,
#                  'insert_me': 'Hello my name is Ayush Sahu'}
#     return render(request, 'webapp/access_records.html', context=date_dict)

class UsersCreateView(CreateView):
    fields = ('first_name', 'last_name', 'email')
    model = User
    template_name = 'webapp/users.html'

class UsersListView(ListView):
    model = User
    template_name = 'webapp/user_list.html'

class UsersDetailView(DetailView):
    model = User
    template_name = 'webapp/user_detail.html'

class UsersUpdateView(UpdateView):
    fields = ('first_name', 'last_name', 'email')
    model = User
    template_name = 'webapp/users.html'

class UsersDeleteView(DeleteView):
    model = User
    success_url = reverse_lazy("webapp:userlist")


# class UsersDetailView(DetailView):
#     # context_object_name = 'user_detail'
#     model = User
#     # template_name = 'basic_app/users.html'


# def users(request):
#     form = forms.NewUser()
#
#     if request.method == 'POST':
#         form = forms.NewUser(request.POST)
#         if form.is_valid():
#             form.save(commit = True)
#             return index(request)
#         else:
#             print ("Error form invalid")
#     return render(request, 'webapp/users.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account not Active")

        else:
            print ("Someone tried to login & failed")
            print ("Username: {} and Password: {}".format(username, password))

            return HttpResponse("invalid login")

    else:
        return render(request, 'webapp/login.html', {})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("You are logged in!")

website_project/templates/webapp/access_records.html
{% extends "webapp/base.html" %}

{% block body_block %}

<h1>Hi Welcome to My Django Revision</h1>
<!-- {{ insert_me }} -->

<h2>Here are your access records</h2>
<div class="djangtwo">
  {% if access_records %}
  <table border="1px soild black">
    <thead>
      <th>Site Name</th>
      <th>Date Accessed</th>
    </thead>
    {% for acc in access_records %}
    <tr>
      <td>{{ acc.name }}</td>
      <td>{{ acc.date }}</td>
    </tr>
    {% endfor %}
  </table>
  {% else %}
  <p>No access records found!</p>
  {% endif %}
</div>
{% endblock %}

website_project/templates/webapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-item nav-link" href="{% url 'webapp:register' %}">Register</a>
        <a class="nav-item nav-link" href="{% url 'webapp:users' %}">Users</a>
        <a class="nav-item nav-link" href="{% url 'webapp:accrec' %}">Access Records</a>
        {% if user.is_authenticated %}
        <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
        {% else %}
        <a class="nav-item nav-link" href="{% url 'webapp:user_login' %}">Login</a>
        {% endif %}
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      <!-- Anything ouotside of it will be inherited -->
      {% endblock %}
    </div>
  </body>
</html>

website_project/templates/webapp/form_page.html
{% extends "webapp/base.html" %}
{% load static %}

{% block body_block %}
<div class="jumbotron">
  {% if registered %}
  <h1>Thankyou for registering!</h1>
  {% else %}
  <h1>Register here</h1>
  <h3>Fill out the form</h3>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" class="btn btn-primary" value="Register">
  </form>
  {% endif %}
</div>

{% endblock %}

website_project/templates/webapp/index.html
{% extends "webapp/base.html" %}

{% block body_block %}
<div class="jumbotron">
  <h1><a href="{% url 'webapp:register' %}">Go to webapp/register to fill out form</a></h1>
  <h1><a href="{% url 'webapp:users' %}">Go to webapp/users to signup</a></h1>
  <h1><a href="{% url 'admin:index' %}">Go to Admin page</a></h1>

  <!-- {{ text|cut:'hello' }} -->
</div>
{% endblock %}

website_project/templates/webapp/login.html
{% extends "webapp/base.html" %}

{% block body_block %}
<div class="jumbotron">
  <h1>Please Login</h1>
  <form action="{% url 'webapp:user_login' %}" method="POST">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter your uername">
    <br>
    <label for="password">Password:</label>
    <input type="password" name="password">
    <br>
    <input type="submit" value="login">

  </form>
</div>

{% endblock %}

website_project/templates/webapp/user_confirm_delete.html
{% extends 'webapp/base.html' %}


{% block body_block %}

<h1>Delete {{ user.first_name }}?</h1>

<form method="POST">
  {% csrf_token %}
  <input type="submit" class="btn btn-large btn-danger" value="Delete">
  <a href="{% url 'webapp:userdetail' pk=user.pk %}">Cancel</a>
</form>

{% endblock %}

website_project/templates/webapp/user_detail.html
{% extends 'webapp/base.html' %}


{% block body_block %}

<div class="jumbotron">
  <h2>User Details:</h2>
  <p>First Name: {{ user.first_name }}</p>
  <p>Last Name: {{ user.last_name }}</p>
  <p>Email id: {{ user.email }}</p>
</div>

<a href="{% url 'webapp:userlist' %}" class="btn btn-large btn-primary">Go back to list</a>
<br>
<a href="{% url 'webapp:userupdate' pk=user.pk %}" class="btn btn-large btn-warning">Update</a>
<br>
<a href="{% url 'webapp:userdelete' pk=user.pk %}" class="btn btn-large btn-danger">Delete</a>

{% endblock %}

website_project/templates/webapp/user_list.html
{% extends "webapp/base.html" %}

{% block body_block %}

<div class="jumbotron">
  <h1>Welcome to the list of all Users</h1>
  <h2>Here are all the users:</h2>
  <ol>
    {% for user in user_list %}
    <h2><li><a href="{{ user.id }}">{{ user.first_name }}</a></li></h2>
    {% endfor %}
  </ol>
</div>

{% endblock %}

website_project/templates/webapp/users.html
{% extends "webapp/base.html" %}

{% block body_block %}

<h1>
  {% if not form.instance.pk %}
  Create School
  {% else %}
  Update School
  {% endif %}
</h1>
</div>
<div class="container">
<form method="POST">
{{ form.as_p }}
{% csrf_token %}
{% if not form.instance.pk %}
<input type="submit" class="btn btn-primary" name="submit" value="Sign Up">
{% else %}
<input type="submit" class="btn btn-primary" name="submit" value="Update">
{% endif %}
</form>
</div>
<br>
<br>
<div class="container">
  <a class="btn btn-warning" href="{% url 'webapp:userlist' %}">List of Users</a>


{% endblock %}